version: "3.9"

services:
  api-gateway:
    image: ghcr.io/samithiwat/samithiwat-backend-gateway:master
    container_name: api-gateway
    restart: unless-stopped
    networks:
      - samithiwat-prod
    depends_on:
      - samithiwat-prod-service
      - auth-service
    volumes:
      - ./service/prod/gateway/config:/app/config
    ports:
      - ${GATEWAY_PORT}:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`api.samithiwat.dev`)"
      - "traefik.http.routers.api-gateway.entrypoints=web"
      - "traefik.docker.network=traefik-net"

  auth-service:
    image: ghcr.io/samithiwat/samithiwat-backend-auth:master
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - samithiwat-prod
      - database
    ports:
      - ${AUTH_SERVICE_PORT}:3001

  samithiwat-service:
    image: ghcr.io/samithiwat/samithiwat-backend:master
    container_name: samithiwat-service
    restart: unless-stopped
    networks:
      - samithiwat-prod
      - database
    volumes:
      - ./service/prod/samithiwat/config:/app/config
    ports:
      - ${SAMITHIWAT_SERVICE_PORT}:3002

networks:
  samithiwat-prod:
    name: samithiwat-prod
  database:
    name: database
    external: true
  traefik-net:
    name: traefik-net
    external: true
