version: "3.9"

services:
  api-gateway:
    image: ghcr.io/samithiwat/samithiwat-backend-gateway:dev
    container_name: api-gateway-dev
    restart: unless-stopped
    networks:
      - samithiwat-dev
    depends_on:
      - samithiwat-service-dev
      - auth-service-dev
    volumes:
      - ./service/dev/gateway/config:/app/config
    ports:
      - ${GATEWAY_PORT}:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`pdev.samithiwat.dev`)"
      - "traefik.http.routers.api-gateway.entrypoints=web"
      - "traefik.docker.network=traefik-net"

  auth-service:
    image: ghcr.io/samithiwat/samithiwat-backend-auth:dev
    container_name: auth-service-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    networks:
      - samithiwat-dev
      - database
    ports:
      - ${AUTH_SERVICE_PORT}:3001

  samithiwat-service:
    image: ghcr.io/samithiwat/samithiwat-backend:dev
    container_name: samithiwat-service-dev
    restart: unless-stopped
    networks:
      - samithiwat-dev
      - database
    volumes:
      - ./service/dev/samithiwat/config:/app/config
    ports:
      - ${SAMITHIWAT_SERVICE_PORT}:3002

networks:
  samithiwat-dev:
    name: samithiwat-dev
  database:
    name: database
    external: true
  traefik-net:
    name: traefik-net
    external: true
