version: "3.9"

services:
  api-gateway-local:
    image: ghcr.io/samithiwat/samithiwat-backend-gateway:dev
    container_name: api-gateway-local
    restart: unless-stopped
    networks:
      - samithiwat-local
    depends_on:
      - samithiwat-service-local
      - auth-service-local
    volumes:
      - ./service/local/gateway/config:/app/config
    ports:
      - ${GATEWAY_PORT}:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gateway.rule=Host(`localhost`)"
      - "traefik.http.routers.api-gateway.entrypoints=web"
      - "traefik.docker.network=traefik-net"

  auth-service-local:
    image: ghcr.io/samithiwat/samithiwat-backend-auth:dev
    container_name: auth-service-local
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - samithiwat-local
      - database
    ports:
      - ${AUTH_SERVICE_PORT}:3001

  samithiwat-service-local:
    image: ghcr.io/samithiwat/samithiwat-backend:dev
    container_name: samithiwat-service-local
    restart: unless-stopped
    depends_on:
      - auth-service-local
    networks:
      - samithiwat-local
      - database
    volumes:
      - ./service/local/samithiwat/config:/app/config
    ports:
      - ${SAMITHIWAT_SERVICE_PORT}:3002

  samithiwat-blog-service-local:
    image: ghcr.io/samithiwat/samithiwat-backend-blog:dev
    container_name: samithiwat-service-blog-local
    restart: unless-stopped
    depends_on:
      - samithiwat-service-local
    networks:
      - samithiwat-local
      - database
    env_file:
      - .env.local
    ports:
      - ${SAMITHIWAT_BLOG_SERVICE_PORT}:3008

networks:
  samithiwat-local:
    name: samithiwat-local
  database:
    name: database
    external: true
  traefik-net:
    name: traefik-net
    external: true
